// 24 mouth-watering sample food items across 8 categories with high-resolution food photography URLs
const sampleFoods = [
  // --- PIZZA ---
  {
    name: 'Margherita Basilico Pizza',
    description: 'Crisp hand-stretched crust topped with rich San Marzano tomato sauce, fresh buffalo mozzarella, and fragrant garden basil leaves.',
    price: 349,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Mozzarella', 'San Marzano Tomato Sauce', 'Fresh Basil', 'Extra Virgin Olive Oil', 'Parmesan'],
    isVeg: true,
    rating: 4.8,
    available: true,
  },
  {
    name: 'Fiery Paneer Tikka Pizza',
    description: 'Char-grilled cottage cheese cubes tossed in spicy tandoori marinade, sliced bell peppers, red onions, and melted mozzarella cheese.',
    price: 429,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Tandoori Paneer', 'Green Capsicum', 'Red Onions', 'Mozzarella', 'Tandoori Sauce'],
    isVeg: true,
    rating: 4.7,
    available: true,
  },
  {
    name: 'Smokey BBQ Chicken Feast Pizza',
    description: 'Tender pulled smoked barbecue chicken, sweet corn, caramelised onions, and double mozzarella on our signature herb crust.',
    price: 499,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Smoked BBQ Chicken', 'Caramelised Onions', 'Sweet Corn', 'Mozzarella', 'BBQ Drizzle'],
    isVeg: false,
    rating: 4.9,
    available: true,
  },

  // --- BURGER ---
  {
    name: 'Crunchy Veg Supreme Burger',
    description: 'Crispy spiced vegetable and potato patty topped with tangy burger relish, fresh lettuce, tomato slices, and cheddar cheese in a brioche bun.',
    price: 199,
    category: 'Burger',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Spiced Veggie Patty', 'Cheddar Cheese', 'Iceberg Lettuce', 'Tomato', 'Brioche Bun', 'Herb Mayo'],
    isVeg: true,
    rating: 4.6,
    available: true,
  },
  {
    name: 'Double Cheeseburger Deluxe',
    description: 'Two flame-grilled juicy chicken patties loaded with melted Monterey Jack cheese, dill pickles, and secret signature diner sauce.',
    price: 299,
    category: 'Burger',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Grilled Chicken Patties', 'Double Melted Cheese', 'Pickles', 'Signature Sauce', 'Toasted Sesame Bun'],
    isVeg: false,
    rating: 4.8,
    available: true,
  },
  {
    name: 'Tandoori Crispy Paneer Burger',
    description: 'Golden fried crumbed cottage cheese steak infused with rich tandoori spices, crunchy cabbage slaw, and mint yoghurt dressing.',
    price: 249,
    category: 'Burger',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Crispy Paneer Steak', 'Mint Mayo', 'Crunchy Slaw', 'Tomatoes', 'Brioche Bun'],
    isVeg: true,
    rating: 4.7,
    available: true,
  },

  // --- INDIAN ---
  {
    name: 'Royal Shahi Paneer Butter Masala',
    description: 'Velvety cottage cheese cubes simmered in a slow-cooked cashew nut, butter, and fragrant vine tomato gravy with kasturi methi.',
    price: 360,
    category: 'Indian',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Fresh Malai Paneer', 'Cashew Cream', 'Butter', 'Tomatoes', 'Kasturi Methi', 'Cardamom'],
    isVeg: true,
    rating: 4.9,
    available: true,
  },
  {
    name: 'Old Delhi Butter Chicken',
    description: 'Succulent boneless tandoori chicken cooked in an iconic buttery tomato makhani gravy infused with aromatic whole spices and fresh cream.',
    price: 440,
    category: 'Indian',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Boneless Tandoori Chicken', 'Makhani Gravy', 'Pure Butter', 'Fresh Cream', 'Ginger Juliennes'],
    isVeg: false,
    rating: 4.9,
    available: true,
  },
  {
    name: 'Hyderabadi Dum Biryani',
    description: 'Aromatic aged Basmati rice layered with spiced marinated vegetables, saffron milk, fried onions, and served with cucumber raita.',
    price: 320,
    category: 'Indian',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Aged Basmati Rice', 'Assorted Vegetables', 'Saffron', 'Brown Onions (Birista)', 'Mint', 'Raita'],
    isVeg: true,
    rating: 4.8,
    available: true,
  },

  // --- CHINESE ---
  {
    name: 'Hakka Chilli Garlic Noodles',
    description: 'Wok-tossed noodles with shredded cabbage, crunchy carrots, bell peppers, scallions, and a punchy garlic chilli soya sauce.',
    price: 240,
    category: 'Chinese',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Wheat Noodles', 'Bell Peppers', 'Carrots', 'Spring Onions', 'Chilli Garlic Sauce', 'Sesame Oil'],
    isVeg: true,
    rating: 4.6,
    available: true,
  },
  {
    name: 'Crispy Veg Manchurian Gravy',
    description: 'Golden fried mixed vegetable dumplings simmered in an umami-packed dark soya, ginger, and green chilli sauce.',
    price: 260,
    category: 'Chinese',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Cabbage & Carrot Dumplings', 'Dark Soy Sauce', 'Ginger & Garlic', 'Green Chillies', 'Coriander'],
    isVeg: true,
    rating: 4.7,
    available: true,
  },
  {
    name: 'Szechuan Chicken Fried Rice',
    description: 'Fragrant jasmine rice wok-tossed with spicy Szechuan peppercorns, diced chicken, eggs, scallions, and toasted sesame.',
    price: 290,
    category: 'Chinese',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Steamed Rice', 'Tender Chicken Cubes', 'Scrambled Egg', 'Szechuan Sauce', 'Spring Onion'],
    isVeg: false,
    rating: 4.8,
    available: true,
  },

  // --- SOUTH INDIAN ---
  {
    name: 'Crispy Mysore Masala Dosa',
    description: 'Golden fermented rice-lentil crepe smeared with spicy red chilli-garlic chutney, stuffed with tempered spiced mashed potatoes, served with sambar and fresh coconut chutney.',
    price: 180,
    category: 'South Indian',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Crispy Dosa Batter', 'Mysore Chutney', 'Spiced Potato Masala', 'Toor Dal Sambar', 'Fresh Coconut Chutney'],
    isVeg: true,
    rating: 4.9,
    available: true,
  },
  {
    name: 'Fluffy Ghee Idli & Crispy Vada Combo',
    description: 'Steamed fluffy rice cakes drizzled with pure cow ghee paired with crunchy golden medu vadas, piping hot sambar, and two freshly ground chutneys.',
    price: 160,
    category: 'South Indian',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Steamed Idlis', 'Medu Vada', 'Pure Desi Ghee', 'Tangy Sambar', 'Tomato & Coconut Chutneys'],
    isVeg: true,
    rating: 4.7,
    available: true,
  },
  {
    name: 'Chettinad Spicy Paneer Roast',
    description: 'Fragrant dry preparation of cottage cheese roasted in stone-ground Chettinad pepper and coriander seed spices with fresh curry leaves.',
    price: 280,
    category: 'South Indian',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Fresh Paneer', 'Chettinad Masala', 'Curry Leaves', 'Black Pepper', 'Coconut Oil'],
    isVeg: true,
    rating: 4.8,
    available: true,
  },

  // --- SNACKS ---
  {
    name: 'Crispy Peri-Peri French Fries',
    description: 'Thick-cut golden potato fries tossed generously in zesty African peri-peri spice blend, served with garlic herb dip.',
    price: 149,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Potato Fries', 'Peri-Peri Seasoning', 'Garlic Aioli', 'Sea Salt'],
    isVeg: true,
    rating: 4.6,
    available: true,
  },
  {
    name: 'Delhi Street Samosa Chaat',
    description: 'Crushed crispy spiced potato samosas layered with warm chickpea curry, whipped sweet yoghurt, tangy tamarind chutney, and fresh mint chutney.',
    price: 160,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Crispy Samosa', 'Chole Gravy', 'Sweet Curd', 'Imli Chutney', 'Sev', 'Pomegranate'],
    isVeg: true,
    rating: 4.9,
    available: true,
  },
  {
    name: 'Loaded Nachos Grande',
    description: 'Stone-ground corn tortilla chips baked with melted jalapeño cheese sauce, black beans, pico de gallo salsa, and sour cream.',
    price: 260,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Corn Tortillas', 'Warm Cheese Sauce', 'Jalapeños', 'Pico de Gallo', 'Sour Cream'],
    isVeg: true,
    rating: 4.7,
    available: true,
  },

  // --- DESSERTS ---
  {
    name: 'Warm Choco Lava Volcano Cake',
    description: 'Decadent Belgian dark chocolate cake with a molten, oozing chocolate center, dusted with cocoa powder and served warm.',
    price: 180,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Belgian Dark Chocolate', 'Butter', 'Cocoa Powder', 'Vanilla Extract', 'Flour'],
    isVeg: true,
    rating: 4.9,
    available: true,
  },
  {
    name: 'Royal Shahi Gulab Jamun with Rabri',
    description: 'Soft khoya dumplings deep-fried to golden perfection, soaked in rose cardamom sugar syrup, served warm over chilled saffron rabri.',
    price: 190,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Mawa/Khoya', 'Rose Syrup', 'Cardamom', 'Pistachios', 'Chilled Thick Rabri'],
    isVeg: true,
    rating: 4.9,
    available: true,
  },
  {
    name: 'Classic New York Cheesecake',
    description: 'Velvety smooth baked cream cheese filling resting on a buttery honey graham cracker crust, topped with fresh strawberry compote.',
    price: 240,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Philadelphia Cream Cheese', 'Graham Crackers', 'Butter', 'Fresh Strawberry Glaze'],
    isVeg: true,
    rating: 4.8,
    available: true,
  },

  // --- BEVERAGES ---
  {
    name: 'Alphonso Mango Frappe / Lassi',
    description: 'Thick, creamy blend of organic curd and pure Ratnagiri Alphonso mango pulp garnished with saffron strands and crushed pistachios.',
    price: 140,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Alphonso Mango Pulp', 'Fresh Curd', 'Cardamom', 'Saffron', 'Pistachios'],
    isVeg: true,
    rating: 4.8,
    available: true,
  },
  {
    name: 'Iced Mint & Lemon Mojito',
    description: 'Refreshing sparkling cooler packed with crushed fresh garden mint, zesty lime wedges, brown sugar syrup, and fizzy soda.',
    price: 130,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Fresh Mint', 'Lime Juice', 'Cane Sugar', 'Club Soda', 'Crushed Ice'],
    isVeg: true,
    rating: 4.7,
    available: true,
  },
  {
    name: 'Caramel Hazelnut Cold Coffee',
    description: 'Double espresso shot blended with chilled whole milk, rich roasted hazelnut syrup, and a swirl of buttery salted caramel drizzle.',
    price: 170,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
    ingredients: ['Arabica Espresso', 'Whole Milk', 'Hazelnut Syrup', 'Salted Caramel', 'Whipped Cream'],
    isVeg: true,
    rating: 4.8,
    available: true,
  },
];

module.exports = sampleFoods;
